---
- name: Download and install java-1.7.0-openjdk 
  yum: name={{ item }} state=installed
  with_items: zookeeper_packages

- name: Create the Zookeeper systemd environment file
  template: src=zookeeper.defaults.j2 dest={{ zookeeper_environment_filename }} owner=zookeeper group=zookeeper mode=0644

- name: Create the Zookeeper systemd service file
  template: src=zookeeper.service.j2 dest=/etc/systemd/system/zookeeper.service owner=zookeeper group=zookeeper mode=0644
