---
- name: Converge
  hosts: all
  become: true

  vars:
    - zookeeper_java_version: "{{ lookup('env','JAVA_VERSION') | default('11') }}"
    - zookeeper_ansible_host_group: zookeeper
    - zookeeper_server_variable: facter_ipaddress

  roles:
    - role: ansible-role-zookeeper

  post_tasks:
    - name: Give the Zookeeper time to start
      pause:
        seconds: 30

    - name: Check status to Zookeeper
      command: /opt/zookeeper/bin/zkServer.sh status
      register: zoo_status
      changed_when: false

    - name: Check service running
      fail:
        msg: "Zookeeper service not running"
      when:
        - "'Error contacting service. It is probably not running.' in zoo_status.stdout"

    - name: Check mode status
      fail:
        msg: "Zookeeper mode is not standalone"
      when:
        - "'Mode: leader' not in zoo_status.stdout and 'Mode: follower' not in zoo_status.stdout"
