---
- name: Prepare
  hosts: all
  become: true

  vars:
    - pre_package:
        - name: epel-release
          ansible_os_family: RedHat
    - package:
        - name: facter
          ansible_os_family: RedHat
        - name: ruby
          ansible_os_family: Debian

  roles:
    - role: kevincoakley.ansible-role-package

  post_tasks:
    - gem:
        name: facter
        state: present
        user_install: false
      when:
        - ansible_os_family == 'Debian'
